### ISSUE TITLE
What about the stock LCD screen?

### ISSUE THREAD

**Issue by eduncan911** [KoenVanduffel/CR-6_Klipper#1]
What options do we have with the stock LCD screen and Klipper?  

Just curious if there's any way to use KlipperScreen or some other UX on the stock LCD.  Mostly for the kids to keep an eye on the printer as they don't have their own laptops to remotely monitor it.

Been pinging the author for a bit about portrait mode for KlipperScreen but I don't think it's supported yet.

I do have a BTT PiTFT50 I could use for klipprrscreen.  Just wondering if there's any way to keep the stock screen.

**Comment by KoenVanduffel** [comment]
I have been trying to get DGUS-reloaded-Klipper to work on the T5L screen of the CR6 but haven't manage to get it working yet. DGUS-reloaded-Klipper is made for the very similar T5 screen used on the CR10 in landscape mode. So far for the original Creality screen.

Klipperscreen is a different thing and runs on a screen directly connected to the Raspberry pi. I bought a DFRobot DFR0550 touch screen and connected it to the raspberry just a week ago. Works great! I will share the stl for the box I made to house the pi and the screen soon.

So best would be to go with your BTT screen. Not sure what the exact dimensions are but it might actually be identical to the one DFRobot sells.
I had a quick look and it seems the DFRobot and BTT are the same screens. At least all the dimensions are identical so it should fit in the box I made.

**Comment by eduncan911** [comment]
Thanks!  So I wasn't anything about running the stock LCD with Klipper.  Most likely will do the BTT PiTFT50, yeah, since I already have the BTT SKR Mini V2 on the printer.

The CR6 display actually runs a Linux distro, a stripped down micro version on an ARM CPU.  But, it is Linux.

I've been looking around the Community Firmware edition of the CR6 LCD display firmware to see how they communicate.  I'm hoping it's something that can be turned into a dumb SPI/I2C bus stream, and then direct the Pi's output over that bus.  That's about as far as I'd go.  Well, that and enabling some type of serial device for the touchscreen.

Currently the LCD firmware is built with C headers using specific memory pointers to stream the binary in communications.  Im wondering if there's a "simple" way of directing the binary stream read from an SPI bus.  That would be the easiest.  Then again, someone will need to reverse engineer the pinouts of the screen and such.  Honestly, I have far too many projects/Todo then to go any further.  But hopefully that info helps someone.

I took a look a the `DGUS-reloaded-Klipper` repo.  It's really far behind in features and reading some comments it doesn't look like an easy merge to bring in the latest Klipper.  Doh.

**Comment by KoenVanduffel** [comment]
There is teh DGUS-reloaded and also his newer version DGUSPrinterMenu which works off the newer Klipper versions and is a lot more advanced with customizations possible. I however got already stuck in porting things from T5 to T5L screens and with most of the docs only in Chinese my programming skills are far outgunned.
I managed to port the repo to the newer programming environment and got it to flash and even read a few partial temperatures but got stuck there as I have no idea where to look further. Porting the community screen to Klipper (with the necessary changes) would be great however.

**Comment by eduncan911** [comment]
Leave this open or closed?  For now I'll close it unless you want to bring more attention to it.
