### ISSUE TITLE
Consolidate these CR6-SE scripts to be less confusing

### ISSUE THREAD

**Issue by oliverhbailey** [KoenVanduffel/CR-6_Klipper#10]
Hi,
Would it be too much to ask to provide current information  that doesn't require 6 or 7 separate gitbhub sites open to unwrap this spaghetti bowl that never gets updated.  It gets tiring to try and read through mismatched documentation and scripts because they are never updated or kept current.  

Thank You

PS it gets very difficult where to post these suggestions when there are so many unconnected but related projects,

**Comment by KoenVanduffel** [comment]
I am not sure what you mean. There are 3 other sites I refer to: A video by NERO3D which I cannot improve on so I see no reason to steal his content and repeat it. The others are which repo to download and how to deal with a raspberry pi. Pretty generic stuff where I cannot add anything to. None of these sites need to be open to get Klipper installed once you have the repo flashed and booted your Raspeberry.

Other than that it is a single walk trough.

The very last line refers to the Klipper repo itself to check everything is working as it should after setup is complete. Again I cannot improve on this page.
