### ISSUE TITLE
call from super slicer to start_print macro

### ISSUE THREAD

**Issue by oliverhbailey** [KoenVanduffel/CR-6_Klipper#11]
This gets installed as the start GCode for the CR6-SE when installing klipper and SuperSlicer.  Is this in addition to the CRg.cfg file that gets included, a replacement for that file, or something else?  
Thank You..

This is in SuperSlicer as the current Start GCode:
#G90 ; use absolute coordinates
#M83 ; extruder relative mode
#M140 S{first_layer_bed_temperature[initial_extruder]} ; set final bed temp
#M109 S{first_layer_temperature[initial_extruder]-50} ; set temporary nozzle temp to prevent oozing during homing
#M190 S{first_layer_bed_temperature[initial_extruder]} ; wait for bed temp to stabilize
#G28 ; home all axis
#G1 Z50 F240
#G1 X2 Y10 F3000
#M104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set final nozzle temp
#M109 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; wait for nozzle temp to stabilize
#G1 Z0.28 F240
#G92 E0
#G1 Y140 E10 F1500 ; prime the nozzle
#G1 X2.3 F5000
#G92 E0
#G1 Y10 E10 F1200 ; prime the nozzle
#G92 E0

**Comment by KoenVanduffel** [comment]
As I describe in the klipper_config readme there are 2 maxcro's included int he CR6.cfg:

start_print HOTEND_TEMP={material_print_temperature_layer_0} BED_TEMP={material_bed_temperature_layer_0}

end_print

How these should be called in SuperSlicer I can't tell you I have never used SS.
