### ISSUE TITLE
Recommended changes to TMC2209 settings

### ISSUE THREAD

**Issue by Thinkersbluff** [KoenVanduffel/CR-6_Klipper#2]
FYI:
https://github.com/Klipper3d/klipper/pull/4977

**Comment by KoenVanduffel** [comment]
I just did a print with a few very fine X and Y lines going straight up, probably the ideal test specimen. Need another set, these will go with stealthchop_threshold: 0 and hold current commented out for all 4 steppers.

**Comment by KoenVanduffel** [comment]
After testing for a while I went back to using stealthchop as I cannot detect the advantage of switching stealthchop off. The motor idle current setting I keep removed as that seems to give cleaner prints indeed.
