### ISSUE TITLE
How configure for dgus_reloaded?

### ISSUE THREAD

**Issue by Thinkersbluff** [KoenVanduffel/CR-6_Klipper#3]
The Readme.md for your fork of DGUS_reloaded points to a specially-modified version of Klipper, but I do not see any guidance on how to merge that modified version with your CR6-specific edits.  

Would you please clarify how to adapt that "special" version of Klipper to work with CR6.cfg and where/how to declare the [display] section?  

Might it help your CR6 project if you also fork that special Klipper variant here, to extend that variant with whatever would correctly interpret a .cfg entry like: 

[display T5Lxx]
printer model: CR6-SE

**Comment by KoenVanduffel** [comment]
I have tried to get the CR6 screen to function in Klipper. It is however not the same screen as on the CR10 and I don't have the time and knowledge to do this. Would love if anyone up to the task could do it though.

**Comment by Rukongai** [comment]
I just got this working. I had to recompile the UI and edit some things in the configs for dgus - but it's working. It only works natively in landscape, so i'll either remount my screen or re-do the UI for vertical orientation

I'll share deets tomorrow when my brain is less fried

**Comment by Thinkersbluff** [comment]
Looking forward to reading what you modified to get this working.

I have refactored those "reloaded" screens to run in portrait mode, but I am still chasing-down a couple of run-time bugs that may be specific to my installation or configuration.

1. If I try to Home using the UI, after cycling power, the first activation of the X limit switch triggers an M112 shutdown. Firmware restart allows me to try again, but then the first activation of the Y limit switch causes another shutdown.  Second Firmware Restart allows me to Home correctly, after that. If, instead, I start by sending a G28 command from the Mainsail console, the printer homes correctly, with no shutdowns, and then the UI homing works fine.  I have safe_z_home.py installed and symbolically linked. Wondering whether there is a conflict with the reloaded Klipper.  The same setup works fine with the original Klipper.

2. The Enable/Disable Steppers function does nothing.  Will double-check my DGUS project file, tomorrow.

3. The Info button does not display on the menu.  Cannot figure out why it is implemented as a conditional control anyway. May just make a permanent control of it, like the other settings buttons.

4. Wondering how to access the debug screens.
