### ISSUE TITLE
Klipper does not read/write CONFIG_SAVE results with BTT-SKR-CR6 printer.cfg

### ISSUE THREAD

**Issue by Thinkersbluff** [KoenVanduffel/CR-6_Klipper#6]
The file printer.BTT-SKR-CR6.cfg in klipper_config has two lines at the bottom, which read:

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.

Neither of the Creality printer....cfg files contain those two lines.
When trying to run Klipper with either Fluidd or Mainsail, the CONFIG_SAVE function seems confused by those two lines.  Instead of correctly storing and loading calibration data from the printer.cfg, Klipper writes that header above every saved configuration and then says that nothing has been saved, when I tried to load it.

Removing those two lines fixed my problem. Now Klipper does not write the header any more and it does correctly save and load calibration data.

**Comment by KoenVanduffel** [comment]
Lines removed from the config as proposed. - Thanks for the heads-up I was not aware Klipper was bothered by an empty SAVE_CONFIG section.
